function greetingsCtrl($scope){
	$scope.messages = [
		{
			author:'Dennis',
			img:'/img/greetings/dennis/dennis.jpg',
			mes:''
		},
		{
			author:'Ashley',
			img:'/img/greetings/ashley/ashley.jpg',
			mes:'Happy birthday to an amazing woman I am lucky to call Mom! I hope you have the best day, you deserve nothing less!  Wish we could be there to celebrate with you!'
		},
		{
			author:'Ali',
			img:'/img/greetings/ali/ali.jpg',
			mes:''
		},
		{
			author:'Ryan',
			img:'/img/greetings/ryan/ryan.jpg',
			mes:''
		},
		{
			author:'Garrett',
			img:'/img/greetings/garrett/garrett.jpg',
			mes:'Happy birthday Benita! Hope it is a great one! Hope you can spend some time enjoying your new garden!!'
		},
		{
			author:'Denise',
			img:'/img/greetings/denise/denise.jpg',
			mes:''
		},
		{
			author:'David',
			img:'/img/greetings/david/david.jpg',
			mes:''
		},
		{
			author:'Danny',
			img:'',
			mes:''
		},
		{
			author:'Susan',
			img:'/img/greetings/susan/susan.jpg',
			mes:''
		},
	];
};